---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
 - name: debian-6.0
   driver:
     box: puppetlabs/debian-6.0.10-64-nocm
     box_url: https://atlas.hashicorp.com/puppetlabs/boxes/debian-6.0.10-64-nocm/versions/1.0.2/providers/virtualbox.box
 - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[t3-tinc::default]
    attributes:
